load('ext://helm_remote', 'helm_remote')
load('ext://namespace', 'namespace_create')

customValues = os.path.join(os.getcwd(), 'custom-values.yaml')
def install_elasticsearch(namespace=''):
    namespace_create(namespace, allow_duplicates=True)
    helm_remote('elasticsearch', repo_url='https://charts.bitnami.com/bitnami', namespace=namespace, values=[customValues], set=[], allow_duplicates=True)
