load('ext://helm_remote', 'helm_remote')
load('ext://namespace', 'namespace_create')

def install_kafka(namespace=''):
    namespace_create(namespace, allow_duplicates=True)
    helm_remote('kafka', repo_url='https://charts.bitnami.com/bitnami', namespace=namespace, values=[], set=[], allow_duplicates=True)
